$(document).ready(function(){
    $("#start").click(function(){
        sounds[0].play();
        $("#welcome").fadeOut(650);
    });
    $("#about").click(function(){
        $("#info").fadeIn(650); 
    });
    $("#back").click(function(){
        $("#info").fadeOut(650);   
    });
});
